"""Add validation_sources to paddle

Revision ID: 837c5f246923
Revises: e68bd0ed63d5
Create Date: 2026-03-05 12:04:27.825448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '837c5f246923'
down_revision: Union[str, Sequence[str], None] = 'e68bd0ed63d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paddle_master', sa.Column('validation_sources', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paddle_master', 'validation_sources')
    # ### end Alembic commands ###
