"""add_specs_fields

Revision ID: c87656290b1d
Revises: 
Create Date: 2025-12-29 16:58:12.800952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c87656290b1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paddle_master', sa.Column('specs_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='manual'))
    op.add_column('paddle_master', sa.Column('specs_confidence', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paddle_master', 'specs_confidence')
    op.drop_column('paddle_master', 'specs_source')
    # ### end Alembic commands ###
