"""add slo_logs table

Revision ID: d081a2cccc0e
Revises: 837c5f246923
Create Date: 2026-03-19 17:14:27.438134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd081a2cccc0e'
down_revision: Union[str, Sequence[str], None] = '837c5f246923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_alerts_paddle_id', table_name='price_alerts')
    op.drop_index('ix_price_alerts_user_email', table_name='price_alerts')
    op.drop_table('price_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paddle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['paddle_id'], ['paddle_master.id'], name='price_alerts_paddle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='price_alerts_pkey')
    )
    op.create_index('ix_price_alerts_user_email', 'price_alerts', ['user_email'], unique=False)
    op.create_index('ix_price_alerts_paddle_id', 'price_alerts', ['paddle_id'], unique=False)
    # ### end Alembic commands ###
