"""add_ai_knowledge_base

Revision ID: e68bd0ed63d5
Revises: c87656290b1d
Create Date: 2026-02-25 01:59:24.752041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'e68bd0ed63d5'
down_revision: Union[str, Sequence[str], None] = 'c87656290b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('ai_knowledge_base',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('paddle_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paddle_id'], ['paddle_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_base_source_type'), 'ai_knowledge_base', ['source_type'], unique=False)
    op.drop_index('ix_price_alerts_paddle_id', table_name='price_alerts')
    op.drop_index('ix_price_alerts_user_email', table_name='price_alerts')
    op.drop_table('price_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paddle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['paddle_id'], ['paddle_master.id'], name='price_alerts_paddle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='price_alerts_pkey')
    )
    op.create_index('ix_price_alerts_user_email', 'price_alerts', ['user_email'], unique=False)
    op.create_index('ix_price_alerts_paddle_id', 'price_alerts', ['paddle_id'], unique=False)
    op.drop_index(op.f('ix_ai_knowledge_base_source_type'), table_name='ai_knowledge_base')
    op.drop_table('ai_knowledge_base')
    # ### end Alembic commands ###
